### ISSUE TITLE
Deprecation message php8.1.1 InstanceProfileProvider

### ISSUE THREAD

**Issue by TomaszEspeo** [aws/aws-sdk-php#2367]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
<b>Deprecated</b>: Implicit conversion from float 1.2 to int loses precision in
<b>/var/www/html/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php</b> on line <b>240</b><br />

**Version of AWS SDK for PHP?**
Example: v3.208.7

**Version of PHP (`php -v`)?**
8.1.1

**To Reproduce (observed behavior)**
when calling Aws\Ses\SesClient sendTemplatedEmail method and getting cURL error 28: Connection timed out after 1001 milliseconds 

Exact place of error comes when InstanceProfileProvider's handleRetryableException method is called. 

**Expected behavior**
No deprecation notice.

**Comment by SamRemis** [comment]
Hi @TomaszEspeo,

We don't officially support any 8.0+ versions yet, but I'd like to get this working for you :) I'll put this on my to do list, or accept a PR that fixes this

**Comment by TomaszEspeo** [comment]
thank you for reply, would be cool :)

**Comment by utdrmac** [comment]
#2414 attempted to fix (it has appeared to reduce in most cases) this but I'm still seeing it. @starburst997 @SamRemis 
If it matters, here is my code snipplet:

```
                         printf("- Terminating...\n");

                        $res = $ec2->terminateInstances(array(
                                'InstanceIds' => $instanceIds
                        ));

                        printf("- Waiting for termination confirmation...\n");

                        $res = $ec2->waitUntil('InstanceTerminated', array(
                                'InstanceIds' => $instanceIds
                        ));
```



```
Deprecated: Implicit conversion from float 14999988.37406747 to int loses precision in phar:///Users/ghost/Documents/aws/aws.phar/GuzzleHttp/Handler/CurlMultiHandler.php on line 143
PHP Deprecated:  Implicit conversion from float 14999982.61895962 to int loses precision in phar:///Users/ghost/Documents/aws/aws.phar/GuzzleHttp/Handler/CurlMultiHandler.php on line 143
```

**Comment by allemas** [comment]
Are you raising an Exception? 

I fixed my "PHP Deprecated" notice in src/Credentials/InstanceProfileProvider.php line 262  by adding (int) casting.
like this : 
```
sleep((int) pow(1.2, $this->attempts));`
```

**Comment by sMorten** [comment]
> Hi @TomaszEspeo,
> 
> We don't officially support any 8.0+ versions yet, but I'd like to get this working for you :) I'll put this on my to do list, or accept a PR that fixes this

Any update on this? @SamRemis

**Comment by ElijahLynn** [comment]
Hi @SamRemis, 

Can you get this prioritized?

PHP 7.4 is End of Life in 10 days, on Nov. 28 2022. 

https://www.php.net/supported-versions.php

![image](https://user-images.githubusercontent.com/1504756/202488715-febf848f-8acb-4e49-848d-8a7bf4033910.png)

**Comment by stobrien89** [comment]
Hi all, 

It seems https://github.com/aws/aws-sdk-php/pull/2447/files should have fixed this— is anyone still experiencing this particular issue?  

Further modernization of the SDK will coincide with our deprecation of 7.2 and below, which is slated to happen early next year.

**Comment by ElijahLynn** [comment]
Sorry, I had commented on the wrong issue and see now that my issue has already been reported https://github.com/aws/aws-sdk-php/issues/2558 and there is a new tag out for that one.

**Comment by stobrien89** [comment]
Closing this for now, but please let us know if you're still having issues!
