### ISSUE TITLE
S3, check if file exists => Error parsing XML: String could not be parsed as XML

### ISSUE THREAD

**Issue by mumhftm** [aws/aws-sdk-php#3181]
### Describe the bug

Calling `Aws\S3\S3Client->doesObjectExistV2() `

leads to the exception:
`Error parsing response for HeadObject: AWS parsing error: Error parsing XML: String could not be parsed as XML at /aws/aws-sdk-php/src/S3/Parser/S3Parser.php:74`

- Happens **since V351.10.** 
- Last working version is 351.9. 
- I tested almost all versions between 350.0 up to 356.11

Use no special chars (no whitespace or similar) in filenames of files on S3. Paths are simple, e.g. _invoices/2025/506/2025-08-27_506-000030655_invoice.pdf_

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Expected Behavior

It should just return a boolean, indicating whether or not the file exists on S3.

### Current Behavior

It leads to the described exception.
Happens with all files.

### Reproduction Steps

1. Place a file to an S3 bucket
2. Assign permissions to access the S3 bucket to an EC2 (with Ubuntu)
3. Install the AWS lib and PHP 
4. Call the doesObjectExistV2()

### Possible Solution

I would - obviously - review the changes:
https://github.com/aws/aws-sdk-php/compare/3.351.9...3.351.10

### SDK version used

351.10

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.3.6, Ubuntu 24.04.1, EC2, S3 Bucket, Access through assigned IAM role

**Comment by mumhftm** [comment]
Could it be related to #3173  ?

**Comment by stobrien89** [comment]
Hi @mumhftm,

Sorry to hear about the issues.  Looking into this now.

**Comment by stobrien89** [comment]
@mumhftm,

I wasn't able to reproduce, but this does seem similar to the issue you linked.  It seems like the server is sending back a body, or some utility is converting the `HEAD` response to a `GET` response.  Would you be able to provide debug logs by adding `'debug' => true` to your client configuration and providing the output for a failed call? Be sure to redact any sensitive information like account numbers.

It doesn't appear that you're using any 3rd party s3 implementations or libraries to access S3, but if you are, could you provide the names of the packages or services you're using?

**Comment by mumhftm** [comment]
Hi @stobrien89 

Thanks.

The problem happens with Laravel 12, using league/flysystem-aws-s3-v3 V3.29 on top of aws-sdk-php. 
Bug #3173 seems to be related to Laravel as well.

My investigations so far:
1. Creating an isolated example with a simple config doesn't lead to the exception.
2. So I added a log to see what config is passed to `new S3Client()`. It might be relevant for further investigations, but even the very same config didn't lead to the exception in the isolated example: `"driver":"s3","key":null,"secret":null,"region":"eu-central-2","bucket":"company-portal","url":null,"endpoint":null,"use_path_style_endpoint":false,"throw":true,"report":true,"root":"stage","version":"latest"`
3. Therefore, the difference might be something happening between instantiating S3Client and calling `doesObjectExistV2($bucket, $pathToFile, false, []);`
4. Double checked the reported problem: It also happens with most recent version 3.356.12, while it works with 3.351.9
5. All tests were done with calling doesObjectExistV2() where the file actually exists.
6. I hope you can see more with the debug output, which was done with 3.356.12

Here is the debug output (redacted sensitive informations, so things like filename-lengts might mismatch if that's relevant somewhere):

```
-> Entering step init, name 'idempotency_auto_fill'
---------------------------------------------------

  command was set to array(3) {
    ["instance"]=>
    string(32) "00000000000006bf0000000000000000"
    ["name"]=>
    string(10) "HeadObject"
    ["params"]=>
    array(4) {
      ["Bucket"]=>
      string(15) "company-portal"
      ["Key"]=>
      string(81) "application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf"
      ["@http"]=>
      array(1) {
        ["debug"]=>
        resource(875) of type (stream)
      }
      ["@context"]=>
      array(0) {
      }
    }
  }
  
  request was set to array(0) {
  }
  


-> Entering step init, name 's3.ssec'
-------------------------------------

  no changes


-> Entering step init, name 's3.source_file'
--------------------------------------------

  no changes


-> Entering step init, name 's3.save_as'
----------------------------------------

  no changes


-> Entering step init, name 's3.location'
-----------------------------------------

  no changes


-> Entering step init, name 's3.auto_encode'
--------------------------------------------

  no changes


-> Entering step init, name 's3.head_object'
--------------------------------------------

  command.params.@http.decode_content was set to 


-> Entering step validate, name 'validation'
--------------------------------------------

  no changes


-> Entering step validate, name 'input_validation_middleware'
-------------------------------------------------------------

  no changes


-> Entering step build, name 'auth-selection'
---------------------------------------------

  command.params.@context.signature_version was set to v4


-> Entering step build, name 'endpoint-resolution'
--------------------------------------------------

  command.params.@context.signature_version changed from v4 to s3v4
  command.params.@context.signing_service was set to s3
  command.params.@context.signing_region was set to eu-central-2


-> Entering step build, name 'builder'
--------------------------------------

  request.instance was set to 00000000000006210000000000000000
  request.method was set to HEAD
  request.headers was set to array(2) {
    ["X-Amz-Security-Token"]=>
    string(7) "[TOKEN]"
    ["Host"]=>
    array(1) {
      [0]=>
      string(45) "company-portal.s3.eu-central-2.amazonaws.com"
    }
  }
  
  request.scheme was set to https
  request.path was set to /application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf


-> Entering step build, name 's3.check_empty_path_with_query'
-------------------------------------------------------------

  no changes


-> Entering step build, name 'ApiCallMonitoringMiddleware'
----------------------------------------------------------

  no changes


-> Entering step build, name ''
-------------------------------

  request.instance changed from 00000000000006210000000000000000 to 00000000000007690000000000000000
  request.headers.X-Amz-User-Agent was set to array(1) {
    [0]=>
    string(0) ""
  }
  


-> Entering step build, name 'endpoint_parameter'
-------------------------------------------------

  no changes


-> Entering step build, name 'EndpointDiscoveryMiddleware'
----------------------------------------------------------

  no changes


-> Entering step build, name 'request-compression'
--------------------------------------------------

  no changes


-> Entering step build, name 'recursion-detection'
--------------------------------------------------

  no changes


-> Entering step build, name 's3.checksum'
------------------------------------------

  no changes


-> Entering step build, name 's3.content_type'
----------------------------------------------

  no changes


-> Entering step build, name 's3.bucket_endpoint_arn'
-----------------------------------------------------

  no changes


-> Entering step sign, name 'StreamRequestPayloadMiddleware'
------------------------------------------------------------

  no changes


-> Entering step sign, name 'invocation-id'
-------------------------------------------

  request.instance changed from 00000000000007690000000000000000 to 000000000000076a0000000000000000
  request.headers.aws-sdk-invocation-id was set to array(1) {
    [0]=>
    string(32) "{potential_sensitive_string_removed}"
  }
  


-> Entering step sign, name 'retry'
-----------------------------------

  request.instance changed from 000000000000076a0000000000000000 to 000000000000075d0000000000000000
  request.headers.aws-sdk-retry was set to array(1) {
    [0]=>
    string(3) "0/0"
  }
  


-> Entering step sign, name 'signer'
------------------------------------

  request.instance changed from 000000000000075d0000000000000000 to 000000000000076c0000000000000000
  request.headers.x-amz-content-sha256 was set to array(1) {
    [0]=>
    string(64) "{potential_sensitive_string_removed}"
  }
  
  request.headers.X-Amz-Date was set to array(1) {
    [0]=>
    string(16) "20250906T105111Z"
  }
  
  request.headers.Authorization was set to array(1) {
    [0]=>
    string(252) "AWS4-HMAC-SHA256 Credential=[KEY]/20250906/eu-central-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-user-agent, Signature=[SIGNATURE]
  }
  


-> Entering step sign, name 'user-agent'
----------------------------------------

  request.instance changed from 000000000000076c0000000000000000 to 00000000000007270000000000000000
  request.headers.User-Agent was set to array(1) {
    [0]=>
    string(77) "aws-sdk-php/3.356.12 ua/2.1 OS/Linux#6.14.0-1012-aws lang/php#8.3.6 m/P,Z,0,b"
  }
  


-> Entering step sign, name 's3.expires_parsing'
------------------------------------------------

  no changes


-> Entering step sign, name 's3.put_object_url'
-----------------------------------------------

  no changes


-> Entering step sign, name 's3.permanent_redirect'
---------------------------------------------------

  no changes


-> Entering step attempt, name 'ApiCallAttemptMonitoringMiddleware'
-------------------------------------------------------------------

  no changes

<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [CONNECT] 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [MIME_TYPE_IS] message: "application/pdf" 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [FILE_SIZE_IS] message: "Content-Length: 130655" bytes_max: "130655" 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [PROGRESS] bytes_max: "130655" 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [COMPLETED] bytes_max: "130655" 

<- Leaving step attempt, name 'ApiCallAttemptMonitoringMiddleware'
------------------------------------------------------------------

  error was set to array(13) {
    ["instance"]=>
    string(32) "00000000000007f50000000000000000"
    ["class"]=>
    string(28) "Aws\S3\Exception\S3Exception"
    ["message"]=>
    string(110) "Error parsing response for HeadObject: AWS parsing error: Error parsing XML: String could not be parsed as XML"
    ["file"]=>
    string(64) "/path/to/application/vendor/aws/aws-sdk-php/src/S3/Parser/S3Parser.php"
    ["line"]=>
    int(74)
    ["trace"]=>
    string(14497) "#0 /path/to/application/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(126): Aws\S3\Parser\S3Parser->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Response))
  #1 /path/to/application/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(93): Aws\WrappedHttpHandler->parseResponse(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), Array)
  #2 /path/to/application/vendor/guzzlehttp/promises/src/Promise.php(209): Aws\WrappedHttpHandler->Aws\{closure}(Object(GuzzleHttp\Psr7\Response))
  #3 /path/to/application/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
  #4 /path/to/application/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
  #5 /path/to/application/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
  #6 /path/to/application/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
  #7 /path/to/application/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
  #8 /path/to/application/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
  #9 /path/to/application/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
  #10 /path/to/application/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
  #11 /path/to/application/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(330): Aws\AwsClient->execute(Object(Aws\Command))
  #12 /path/to/application/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(121): Aws\S3\S3Client->doesObjectExistV2('company-portal', 'application/company_i...', false, Array)
  #13 /path/to/application/vendor/league/flysystem/src/Filesystem.php(50): League\Flysystem\AwsS3V3\AwsS3V3Adapter->fileExists('company_invoice...')
  #14 /path/to/application/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(212): League\Flysystem\Filesystem->has('company_invoice...')
  #15 /path/to/application/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(468): Illuminate\Filesystem\FilesystemAdapter->exists('company_invoice...')
  #16 /path/to/application/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(363): Illuminate\Filesystem\FilesystemManager->__call('exists', Array)
  #17 /path/to/application/app/Http/Controllers/Admin/FinancialManagement/InvoiceController.php(158): Illuminate\Support\Facades\Facade::__callStatic('exists', Array)
  #18 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): App\Http\Controllers\Admin\FinancialManagement\InvoiceController->downloadInvoice(Object(App\Models\Invoice))
  #19 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/Route.php(265): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Admin\FinancialManagement\InvoiceController), 'downloadInvoice')
  #20 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/Route.php(211): Illuminate\Routing\Route->runController()
  #21 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(822): Illuminate\Routing\Route->run()
  #22 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
  #23 /path/to/application/app/Http/Middleware/CheckRole.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #24 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): App\Http\Middleware\CheckRole->handle(Object(Illuminate\Http\Request), Object(Closure), 'admin|support')
  #25 /path/to/application/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #26 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Auth\Middleware\EnsureEmailIsVerified->handle(Object(Illuminate\Http\Request), Object(Closure))
  #27 /path/to/application/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #28 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
  #29 /path/to/application/app/Http/Middleware/CheckAccountLocked.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #30 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): App\Http\Middleware\CheckAccountLocked->handle(Object(Illuminate\Http\Request), Object(Closure))
  #31 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #32 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
  #33 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(160): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #34 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(91): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest(Object(Illuminate\Http\Request), Object(Closure), Array)
  #35 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
  #36 /path/to/application/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #37 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
  #38 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(87): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #39 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
  #40 /path/to/application/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #41 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
  #42 /path/to/application/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(120): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #43 /path/to/application/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
  #44 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
  #45 /path/to/application/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #46 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
  #47 /path/to/application/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(74): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #48 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
  #49 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #50 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(821): Illuminate\Pipeline\Pipeline->then(Object(Closure))
  #51 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
  #52 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(764): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
  #53 /path/to/application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(753): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
  #54 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
  #55 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
  #56 /path/to/application/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #57 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
  #58 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #59 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
  #60 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
  #61 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #62 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
  #63 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
  #64 /path/to/application/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #65 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
  #66 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(109): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #67 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
  #68 /path/to/application/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #69 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Http\Middleware\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
  #70 /path/to/application/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #71 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
  #72 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/InvokeDeferredCallbacks.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #73 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Foundation\Http\Middleware\InvokeDeferredCallbacks->handle(Object(Illuminate\Http\Request), Object(Closure))
  #74 /path/to/application/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePathEncoding.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #75 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\Http\Middleware\ValidatePathEncoding->handle(Object(Illuminate\Http\Request), Object(Closure))
  #76 /path/to/application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
  #77 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then(Object(Closure))
  #78 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
  #79 /path/to/application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1220): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
  #80 /path/to/application/public/index.php(20): Illuminate\Foundation\Application->handleRequest(Object(Illuminate\Http\Request))
  #81 {main}"
    ["type"]=>
    NULL
    ["code"]=>
    NULL
    ["requestId"]=>
    NULL
    ["statusCode"]=>
    NULL
    ["result"]=>
    NULL
    ["request"]=>
    array(0) {
    }
    ["response"]=>
    array(0) {
    }
  }
  
  Inclusive step time: 0.078334093093872


<- Leaving step sign, name 's3.permanent_redirect'
--------------------------------------------------

  no changes
  Inclusive step time: 0.078439950942993


<- Leaving step sign, name 's3.put_object_url'
----------------------------------------------

  no changes
  Inclusive step time: 0.078497171401978


<- Leaving step sign, name 's3.expires_parsing'
-----------------------------------------------

  no changes
  Inclusive step time: 0.078551054000854


<- Leaving step sign, name 'user-agent'
---------------------------------------

  no changes
  Inclusive step time: 0.078618049621582


<- Leaving step sign, name 'signer'
-----------------------------------

  no changes
  Inclusive step time: 0.078755140304565


<- Leaving step sign, name 'retry'
----------------------------------

  no changes
  Inclusive step time: 0.080081939697266


-> Entering step sign, name 'retry'
-----------------------------------

  command.params.@http.debug changed from resource(875) of type (Unknown)
   to resource(935) of type (stream)
  
  command.params.@http.delay was set to 98
  request.instance changed from 00000000000007270000000000000000 to 00000000000007c80000000000000000
  request.headers.aws-sdk-retry.0 changed from 0/0 to 1/98
  request.headers.x-amz-content-sha256.0 was unset
  request.headers.X-Amz-Date.0 was unset
  request.headers.Authorization.0 was unset
  request.headers.User-Agent.0 was unset


-> Entering step sign, name 'signer'
------------------------------------

  request.instance changed from 00000000000007c80000000000000000 to 00000000000007910000000000000000
  request.headers.x-amz-content-sha256 was set to array(1) {
    [0]=>
    string(64) "{potential_sensitive_string_removed}"
  }
  
  request.headers.X-Amz-Date was set to array(1) {
    [0]=>
    string(16) "20250906T105111Z"
  }
  
  request.headers.Authorization was set to array(1) {
    [0]=>
    string(252) "AWS4-HMAC-SHA256 Credential=[KEY]/20250906/eu-central-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-user-agent, Signature=[SIGNATURE]
  }
  


-> Entering step sign, name 'user-agent'
----------------------------------------

  request.instance changed from 00000000000007910000000000000000 to 00000000000007f70000000000000000
  request.headers.User-Agent was set to array(1) {
    [0]=>
    string(77) "aws-sdk-php/3.356.12 ua/2.1 OS/Linux#6.14.0-1012-aws lang/php#8.3.6 m/P,Z,0,b"
  }
  


-> Entering step sign, name 's3.expires_parsing'
------------------------------------------------

  no changes


-> Entering step sign, name 's3.put_object_url'
-----------------------------------------------

  no changes


-> Entering step sign, name 's3.permanent_redirect'
---------------------------------------------------

  no changes


-> Entering step attempt, name 'ApiCallAttemptMonitoringMiddleware'
-------------------------------------------------------------------

  no changes

<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [CONNECT] 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [MIME_TYPE_IS] message: "application/pdf" 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [FILE_SIZE_IS] message: "Content-Length: 130655" bytes_max: "130655" 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [PROGRESS] bytes_max: "130655" 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [COMPLETED] bytes_max: "130655" 

<- Leaving step attempt, name 'ApiCallAttemptMonitoringMiddleware'
------------------------------------------------------------------

  error.instance changed from 00000000000007f50000000000000000 to 00000000000007ce0000000000000000
  Inclusive step time: 0.16222786903381


<- Leaving step sign, name 's3.permanent_redirect'
--------------------------------------------------

  no changes
  Inclusive step time: 0.16229820251465


<- Leaving step sign, name 's3.put_object_url'
----------------------------------------------

  no changes
  Inclusive step time: 0.16238808631897


<- Leaving step sign, name 's3.expires_parsing'
-----------------------------------------------

  no changes
  Inclusive step time: 0.16244912147522


<- Leaving step sign, name 'user-agent'
---------------------------------------

  no changes
  Inclusive step time: 0.16252112388611


<- Leaving step sign, name 'signer'
-----------------------------------

  no changes
  Inclusive step time: 0.16264200210571


<- Leaving step sign, name 'retry'
----------------------------------

  no changes
  Inclusive step time: 0.16293597221375


-> Entering step sign, name 'retry'
-----------------------------------

  command.params.@http.debug changed from resource(935) of type (Unknown)
   to resource(939) of type (stream)
  
  command.params.@http.delay changed from 98 to 33
  request.instance changed from 00000000000007f70000000000000000 to 00000000000008010000000000000000
  request.headers.aws-sdk-retry.0 changed from 1/98 to 2/33
  request.headers.x-amz-content-sha256.0 was unset
  request.headers.X-Amz-Date.0 was unset
  request.headers.Authorization.0 was unset
  request.headers.User-Agent.0 was unset


-> Entering step sign, name 'signer'
------------------------------------

  request.instance changed from 00000000000008010000000000000000 to 00000000000007c30000000000000000
  request.headers.x-amz-content-sha256 was set to array(1) {
    [0]=>
    string(64) "{potential_sensitive_string_removed}"
  }
  
  request.headers.X-Amz-Date was set to array(1) {
    [0]=>
    string(16) "20250906T105111Z"
  }
  
  request.headers.Authorization was set to array(1) {
    [0]=>
    string(252) "AWS4-HMAC-SHA256 Credential=[KEY]/20250906/eu-central-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-user-agent, Signature=[SIGNATURE]
  }
  


-> Entering step sign, name 'user-agent'
----------------------------------------

  request.instance changed from 00000000000007c30000000000000000 to 00000000000007cd0000000000000000
  request.headers.User-Agent was set to array(1) {
    [0]=>
    string(77) "aws-sdk-php/3.356.12 ua/2.1 OS/Linux#6.14.0-1012-aws lang/php#8.3.6 m/P,Z,0,b"
  }
  


-> Entering step sign, name 's3.expires_parsing'
------------------------------------------------

  no changes


-> Entering step sign, name 's3.put_object_url'
-----------------------------------------------

  no changes


-> Entering step sign, name 's3.permanent_redirect'
---------------------------------------------------

  no changes


-> Entering step attempt, name 'ApiCallAttemptMonitoringMiddleware'
-------------------------------------------------------------------

  no changes

<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [CONNECT] 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [MIME_TYPE_IS] message: "application/pdf" 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [FILE_SIZE_IS] message: "Content-Length: 130655" bytes_max: "130655" 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [PROGRESS] bytes_max: "130655" 
<HEAD https://company-portal.s3.eu-central-2.amazonaws.com/application/company_invoices/2025/506/2025-08-27_112548-00009999_invoice_of_company.pdf> [COMPLETED] bytes_max: "130655" 

<- Leaving step attempt, name 'ApiCallAttemptMonitoringMiddleware'
------------------------------------------------------------------

  no changes
  Inclusive step time: 0.10521411895752


<- Leaving step sign, name 's3.permanent_redirect'
--------------------------------------------------

  no changes
  Inclusive step time: 0.10529613494873


<- Leaving step sign, name 's3.put_object_url'
----------------------------------------------

  no changes
  Inclusive step time: 0.1053478717804


<- Leaving step sign, name 's3.expires_parsing'
-----------------------------------------------

  no changes
  Inclusive step time: 0.10539889335632


<- Leaving step sign, name 'user-agent'
---------------------------------------

  no changes
  Inclusive step time: 0.10546493530273


<- Leaving step sign, name 'signer'
-----------------------------------

  no changes
  Inclusive step time: 0.10561299324036


<- Leaving step sign, name 'retry'
----------------------------------

  no changes
  Inclusive step time: 0.10711598396301


<- Leaving step sign, name 'invocation-id'
------------------------------------------

  no changes
  Inclusive step time: 0.35033917427063


<- Leaving step sign, name 'StreamRequestPayloadMiddleware'
-----------------------------------------------------------

  no changes
  Inclusive step time: 0.35044002532959


<- Leaving step build, name 's3.bucket_endpoint_arn'
----------------------------------------------------

  no changes
  Inclusive step time: 0.35050797462463


<- Leaving step build, name 's3.content_type'
---------------------------------------------

  no changes
  Inclusive step time: 0.35066699981689


<- Leaving step build, name 's3.checksum'
-----------------------------------------

  no changes
  Inclusive step time: 0.35071492195129


<- Leaving step build, name 'recursion-detection'
-------------------------------------------------

  no changes
  Inclusive step time: 0.35077595710754


<- Leaving step build, name 'request-compression'
-------------------------------------------------

  no changes
  Inclusive step time: 0.35082292556763


<- Leaving step build, name 'EndpointDiscoveryMiddleware'
---------------------------------------------------------

  no changes
  Inclusive step time: 0.35087704658508


<- Leaving step build, name 'endpoint_parameter'
------------------------------------------------

  no changes
  Inclusive step time: 0.35092997550964


<- Leaving step build, name ''
------------------------------

  no changes
  Inclusive step time: 0.35100698471069


<- Leaving step build, name 'ApiCallMonitoringMiddleware'
---------------------------------------------------------

  no changes
  Inclusive step time: 0.35108685493469


<- Leaving step build, name 's3.check_empty_path_with_query'
------------------------------------------------------------

  no changes
  Inclusive step time: 0.35152697563171


<- Leaving step build, name 'builder'
-------------------------------------

  no changes
  Inclusive step time: 0.35162901878357


<- Leaving step build, name 'endpoint-resolution'
-------------------------------------------------

  no changes
  Inclusive step time: 0.35207891464233


<- Leaving step build, name 'auth-selection'
--------------------------------------------

  no changes
  Inclusive step time: 0.35264587402344


<- Leaving step validate, name 'input_validation_middleware'
------------------------------------------------------------

  no changes
  Inclusive step time: 0.3589301109314


<- Leaving step validate, name 'validation'
-------------------------------------------

  no changes
  Inclusive step time: 0.35898590087891


<- Leaving step init, name 's3.head_object'
-------------------------------------------

  no changes
  Inclusive step time: 0.3591251373291


<- Leaving step init, name 's3.auto_encode'
-------------------------------------------

  no changes
  Inclusive step time: 0.35916495323181


<- Leaving step init, name 's3.location'
----------------------------------------

  no changes
  Inclusive step time: 0.35920810699463


<- Leaving step init, name 's3.save_as'
---------------------------------------

  no changes
  Inclusive step time: 0.35927486419678


<- Leaving step init, name 's3.source_file'
-------------------------------------------

  no changes
  Inclusive step time: 0.35932207107544


<- Leaving step init, name 's3.ssec'
------------------------------------

  no changes
  Inclusive step time: 0.3593909740448


<- Leaving step init, name 'idempotency_auto_fill'
--------------------------------------------------

  no changes
  Inclusive step time: 0.35964798927307
```

**Comment by stobrien89** [comment]
Hi @mumhftm,

Apologies for the delayed response.  I'm not seeing a body explicitly sent in the response based on the logs, but the error message you're receiving indicates that's what is happening.  Could you tell me which storage back-end is sending the response for these requests?

**Comment by mumhftm** [comment]
Sorry, I don't get what you mean by storage back-end..? I would say S3, but that's obvious..

**Comment by stobrien89** [comment]
I was unclear- I should have asked if you were using (AWS) S3 or any 3rd-party implementations- the flysystem adapter can be used with a number of S3-compatible storage services or self-hosted options like MinIO.  Just to confirm, you are using AWS S3?

**Comment by mumhftm** [comment]
@stobrien89 Thanks for clarifying. Yes, I can confirm, everything AWS (EC2, S3).

**Comment by stobrien89** [comment]
Hi @mumhftm,

I've attempted to reproduce this using flysystem and our latest SDK version and was unable to do so.  Could you confirm exactly which SDK versions you've been using?  And by chance, you're not using WSL, are you?

**Comment by mumhftm** [comment]
Hi @stobrien89 
Thanks.
No, it is: PHP 8.3.6, Ubuntu 24.04.1, EC2, S3 Bucket, Access through assigned IAM role. All AWS.
It happens for instance with 3.356.12 and league/flysystem-aws-s3-v3 V3.29 (the versions by which the debug output was made).

**Comment by mumhftm** [comment]
Hi @stobrien89 
Are there any updates?

**Comment by ablashimov** [comment]
Hello. I have the same problem
php 8.4
laravel - 12.38.1
league/flysystem-aws-s3-v3 - 3.30.1
aws/aws-sdk-php - 3.366.4
And i also use AWS S3 bucket

**Comment by yenfryherrerafeliz** [comment]
Hi @mumhftm and @ablashimov, after investigating this a bit more we found that this issue happens just when requests are done with the stream flag enabled, which with laravel, I dont remember how exactly, but this flag can be set from a global scope, which is not necessarily at SDK client or operation level. What is happening right now is that when stream is enabled in the request, the response comes with a non-seekable stream as body and in such scenario we try to parse the body, but since in head requests the body is empty then we throw an exception complaining about this. 

To remedy this I have pushed a fix on the following [PR](https://github.com/aws/aws-sdk-php/pull/3214). Once we get this change reviewed and merged this issue should be fixed.

Thank you!

**Comment by mumhftm** [comment]
Hey @yenfryherrerafeliz Thanks.
I just tested. The problem still persists with 3.370.1.
Your linked PR is a dead link. Do you know what's the current state?
Thank you

**Comment by yenfryherrerafeliz** [comment]
Hi @mumhftm, I hope you are doing well. We are still in the review process. Here is the [PR](https://github.com/aws/aws-sdk-php/pull/3214). 

Thank you!

**Comment by stobrien89** [comment]
Hi @mumhftm,

Thanks for your patience.  #3214 has been merged, which should address this issue.  Please let us know if you're still having issues after upgrading your SDK version— the latest version should be live within the next hour or two.
